In [3]:
import numpy as np

a = np.array([[1], [2], [3], [4]])
print(a)
b = np.array([[5], [6], [7], [8]])
print(np.append(a, b))

[[1]
 [2]
 [3]
 [4]]
[1 2 3 4 5 6 7 8]


In [44]:
a1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
a1 = a1.reshape((9, 1), order='F')
print(a1)
m = []
m.append(a1)
m.append(a1)
m = np.asarray(m).T[0]
print(m[:, 0])

[[1]
 [4]
 [7]
 [2]
 [5]
 [8]
 [3]
 [6]
 [9]]
[1 4 7 2 5 8 3 6 9]


In [58]:
n = 10
a = np.array([1, 2, 3, 4, 5])
b = np.array(n * [a]).T
print(b)
print(a.T)

[[1 1 1 1 1 1 1 1 1 1]
 [2 2 2 2 2 2 2 2 2 2]
 [3 3 3 3 3 3 3 3 3 3]
 [4 4 4 4 4 4 4 4 4 4]
 [5 5 5 5 5 5 5 5 5 5]]
[1 2 3 4 5]
